//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yubico.YubiKey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access code must be {0} or fewer bytes..
        /// </summary>
        internal static string AccessCodeTooLong {
            get {
                return ResourceManager.GetString("AccessCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The algorithm (Yubico OTP or HMAC-SHA1) must be chosen before you can retrieve the key..
        /// </summary>
        internal static string AlgorithmNotChosen {
            get {
                return ResourceManager.GetString("AlgorithmNotChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YubiKey is already set with the attribute specified..
        /// </summary>
        internal static string AlreadySet {
            get {
                return ResourceManager.GetString("AlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t an application ID associated with this YubiKeyApplication. Either the application is not supported, or is a meta application (like InterIndustry) which does not have an ID..
        /// </summary>
        internal static string ApplicationIdNotFound {
            get {
                return ResourceManager.GetString("ApplicationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application could not be reset..
        /// </summary>
        internal static string ApplicationResetFailure {
            get {
                return ResourceManager.GetString("ApplicationResetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a FirmwareVersion..
        /// </summary>
        internal static string ArgumentMustBeFirmwareVersion {
            get {
                return ResourceManager.GetString("ArgumentMustBeFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto eject timeout cannot be set when touch eject is disabled..
        /// </summary>
        internal static string AutoEjectTimeoutRequiresTouchEjectEnabled {
            get {
                return ResourceManager.GetString("AutoEjectTimeoutRequiresTouchEjectEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authenticator returned a FIDO2 status indicating an error ({0}: {1}).
        /// </summary>
        internal static string BadFido2Status {
            get {
                return ResourceManager.GetString("BadFido2Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unsupported or unknown NDEF record type was encountered. Contact Yubico Support if this error persists..
        /// </summary>
        internal static string BadNdefRecordType {
            get {
                return ResourceManager.GetString("BadNdefRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot both generate and specify a static password..
        /// </summary>
        internal static string BothGenerateAndSpecify {
            get {
                return ResourceManager.GetString("BothGenerateAndSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t specify both TOTP and a challenge..
        /// </summary>
        internal static string BothTotpAndChallenge {
            get {
                return ResourceManager.GetString("BothTotpAndChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCP03 handshake called out-of-order: building an external authenticate response before processing the preceding initialize update response is not possible..
        /// </summary>
        internal static string BuildExternalAuthenticatePriorToLoadInitializeUpdateResponse {
            get {
                return ResourceManager.GetString("BuildExternalAuthenticatePriorToLoadInitializeUpdateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device specified has a different parent from the one it is being merged with..
        /// </summary>
        internal static string CannotMergeDifferentParents {
            get {
                return ResourceManager.GetString("CannotMergeDifferentParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data tag {0} is not available as an alternate..
        /// </summary>
        internal static string CannotUseDataTagAsAlternate {
            get {
                return ResourceManager.GetString("CannotUseDataTagAsAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete a slot that does not contain a configuration..
        /// </summary>
        internal static string CantDeleteEmptySlot {
            get {
                return ResourceManager.GetString("CantDeleteEmptySlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterIndustry is a meta application which cannot be selected directly. Its commands can be issued on other previously selected applications..
        /// </summary>
        internal static string CantSelectInterIndustry {
            get {
                return ResourceManager.GetString("CantSelectInterIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a 16-byte key or choose to generate one, but not both..
        /// </summary>
        internal static string CantSpecifyKeyAndGenerate {
            get {
                return ResourceManager.GetString("CantSpecifyKeyAndGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a six-byte private ID or choose to generate one, but not both..
        /// </summary>
        internal static string CantSpecifyPrivateIdAndGenerate {
            get {
                return ResourceManager.GetString("CantSpecifyPrivateIdAndGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a public ID or choose to use the YubiKey serial number, but not both..
        /// </summary>
        internal static string CantSpecifyPublicIdAndUseSerial {
            get {
                return ResourceManager.GetString("CantSpecifyPublicIdAndUseSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CCID interface is not supported on this YubiKey..
        /// </summary>
        internal static string CcidNotSupported {
            get {
                return ResourceManager.GetString("CcidNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum error..
        /// </summary>
        internal static string ChecksumError {
            get {
                return ResourceManager.GetString("ChecksumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Command/Response operation returned the unexpected value of {0}..
        /// </summary>
        internal static string CommandResponseApduUnexpectedResult {
            get {
                return ResourceManager.GetString("CommandResponseApduUnexpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CBOR response failed to deserialize correctly..
        /// </summary>
        internal static string Ctap2CborDeserializationError {
            get {
                return ResourceManager.GetString("Ctap2CborDeserializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CBOR response contained an indefinite-length array or map, which is unsupported..
        /// </summary>
        internal static string Ctap2CborIndefiniteLength {
            get {
                return ResourceManager.GetString("Ctap2CborIndefiniteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected key was encountered in a CBOR map; expected to find {0} (name &apos;{1}&apos;).
        /// </summary>
        internal static string Ctap2CborUnexpectedKey {
            get {
                return ResourceManager.GetString("Ctap2CborUnexpectedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected value was encountered in a CBOR map..
        /// </summary>
        internal static string Ctap2CborUnexpectedValue {
            get {
                return ResourceManager.GetString("Ctap2CborUnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CTAP2 command was too large to transmit..
        /// </summary>
        internal static string Ctap2CommandTooLarge {
            get {
                return ResourceManager.GetString("Ctap2CommandTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authenticator produced a malformed CTAP2 response..
        /// </summary>
        internal static string Ctap2MalformedResponse {
            get {
                return ResourceManager.GetString("Ctap2MalformedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attestation was provided in an unknown format and cannot be parsed..
        /// </summary>
        internal static string Ctap2UnknownAttestationFormat {
            get {
                return ResourceManager.GetString("Ctap2UnknownAttestationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to decode a response with a failed status word. SCP03 can only verify the successful execution of a command APDU - no verification is possible of status words..
        /// </summary>
        internal static string DecodedResponseStatusWordNotSuccess {
            get {
                return ResourceManager.GetString("DecodedResponseStatusWordNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified device does not support this application..
        /// </summary>
        internal static string DeviceDoesNotSupportApplication {
            get {
                return ResourceManager.GetString("DeviceDoesNotSupportApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type not recognized..
        /// </summary>
        internal static string DeviceTypeNotRecognized {
            get {
                return ResourceManager.GetString("DeviceTypeNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate was not able to parsed..
        /// </summary>
        internal static string FailedParsingCertificate {
            get {
                return ResourceManager.GetString("FailedParsingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FIDO2 status was available in the response to a FIDO2 command..
        /// </summary>
        internal static string Fido2ResponseMissing {
            get {
                return ResourceManager.GetString("Fido2ResponseMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FIDO interface is not supported on this YubiKey..
        /// </summary>
        internal static string HidFidoNotSupported {
            get {
                return ResourceManager.GetString("HidFidoNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HidFido is not available on Windows if the process is not elevated..
        /// </summary>
        internal static string HidFidoWindowsNotElevated {
            get {
                return ResourceManager.GetString("HidFidoWindowsNotElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyboard interface is not supported on this YubiKey..
        /// </summary>
        internal static string HidKeyboardNotSupported {
            get {
                return ResourceManager.GetString("HidKeyboardNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HMAC-SHA1 algorithm requires a 0-64 byte challenge..
        /// </summary>
        internal static string HmacChallengeTooLong {
            get {
                return ResourceManager.GetString("HmacChallengeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key must be exactly 20 bytes..
        /// </summary>
        internal static string HmacKeyWrongSize {
            get {
                return ResourceManager.GetString("HmacKeyWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response APDU indicates further information or action, such as PIN, management key, or touch, is needed to complete the command..
        /// </summary>
        internal static string IncompleteCommandInput {
            get {
                return ResourceManager.GetString("IncompleteCommandInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied AES key was an incorrect length..
        /// </summary>
        internal static string IncorrectAesKeyLength {
            get {
                return ResourceManager.GetString("IncorrectAesKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from the device contained an incorrect card cryptogram. This could be due to incorrect static keys, a skipped or missing response, or man-in-the-middle attack..
        /// </summary>
        internal static string IncorrectCardCryptogram {
            get {
                return ResourceManager.GetString("IncorrectCardCryptogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied ciphertext was not a multiple of the block size in length..
        /// </summary>
        internal static string IncorrectCiphertextLength {
            get {
                return ResourceManager.GetString("IncorrectCiphertextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to derive an incorrectly-sized output..
        /// </summary>
        internal static string IncorrectDerivationLength {
            get {
                return ResourceManager.GetString("IncorrectDerivationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied message digest was an incorrect length..
        /// </summary>
        internal static string IncorrectDigestLength {
            get {
                return ResourceManager.GetString("IncorrectDigestLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied ECC key was an incorrect length..
        /// </summary>
        internal static string IncorrectEccKeyLength {
            get {
                return ResourceManager.GetString("IncorrectEccKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ExternalAuthenticate command was supplied invalid data..
        /// </summary>
        internal static string IncorrectExternalAuthenticateData {
            get {
                return ResourceManager.GetString("IncorrectExternalAuthenticateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing of an InitializeUpdateResponse failed due to an incorrect response length..
        /// </summary>
        internal static string IncorrectInitializeUpdateResponseData {
            get {
                return ResourceManager.GetString("IncorrectInitializeUpdateResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied IV was an incorrect length..
        /// </summary>
        internal static string IncorrectIVLength {
            get {
                return ResourceManager.GetString("IncorrectIVLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password that protects the OATH application and the new password to set are the same..
        /// </summary>
        internal static string IncorrectOathNewPassword {
            get {
                return ResourceManager.GetString("IncorrectOathNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied plaintext was not a multiple of the block size in length..
        /// </summary>
        internal static string IncorrectPlaintextLength {
            get {
                return ResourceManager.GetString("IncorrectPlaintextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device response was not the correct length (a multiple of the block size) to decrypt..
        /// </summary>
        internal static string IncorrectResponseLengthToDecrypt {
            get {
                return ResourceManager.GetString("IncorrectResponseLengthToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from the device contained an incorrect RMAC. This could be due to incorrect static keys, a skipped or missing response, or man-in-the-middle attack..
        /// </summary>
        internal static string IncorrectRmac {
            get {
                return ResourceManager.GetString("IncorrectRmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied RSA key was an incorrect length..
        /// </summary>
        internal static string IncorrectRsaKeyLength {
            get {
                return ResourceManager.GetString("IncorrectRsaKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied static key was an incorrect length..
        /// </summary>
        internal static string IncorrectStaticKeyLength {
            get {
                return ResourceManager.GetString("IncorrectStaticKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied Triple-DES key was an incorrect length..
        /// </summary>
        internal static string IncorrectTripleDesKeyLength {
            get {
                return ResourceManager.GetString("IncorrectTripleDesKeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device response was not long enough to contain an RMAC..
        /// </summary>
        internal static string InsufficientResponseLengthToVerifyRmac {
            get {
                return ResourceManager.GetString("InsufficientResponseLengthToVerifyRmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the response as an int or numeric code is only supported with HMAC-SHA1 mode..
        /// </summary>
        internal static string IntOrCodeOnlyWithHmac {
            get {
                return ResourceManager.GetString("IntOrCodeOnlyWithHmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given algorithm is not valid for the given command..
        /// </summary>
        internal static string InvalidAlgorithm {
            get {
                return ResourceManager.GetString("InvalidAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response data contains invalid data..
        /// </summary>
        internal static string InvalidApduResponseData {
            get {
                return ResourceManager.GetString("InvalidApduResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A challenge must be 8 bytes..
        /// </summary>
        internal static string InvalidChallengeLength {
            get {
                return ResourceManager.GetString("InvalidChallengeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CTAPHID channel ID cannot be null or empty. A valid CTAPHID channel needs to be acquired..
        /// </summary>
        internal static string InvalidChannelId {
            get {
                return ResourceManager.GetString("InvalidChannelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the supplied ciphertext was not valid for the usage..
        /// </summary>
        internal static string InvalidCiphertextLength {
            get {
                return ResourceManager.GetString("InvalidCiphertextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionType None is not an accepted value..
        /// </summary>
        internal static string InvalidConnectionTypeNone {
            get {
                return ResourceManager.GetString("InvalidConnectionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credential cannot be null..
        /// </summary>
        internal static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credential&apos;s account cannot be null..
        /// </summary>
        internal static string InvalidCredentialAccount {
            get {
                return ResourceManager.GetString("InvalidCredentialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of digits for a one-time passcode can only be 6, 7 or 8..
        /// </summary>
        internal static string InvalidCredentialDigits {
            get {
                return ResourceManager.GetString("InvalidCredentialDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credential&apos;s name cannot be more than 64 bytes in length..
        /// </summary>
        internal static string InvalidCredentialNameLength {
            get {
                return ResourceManager.GetString("InvalidCredentialNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validity period for a TOTP passcode can only be 15, 30 or 60 seconds. HOTP should be set to zero..
        /// </summary>
        internal static string InvalidCredentialPeriod {
            get {
                return ResourceManager.GetString("InvalidCredentialPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credential secret can only contain the characters &apos;a-z&apos;, &apos;A-Z&apos;, &apos;2-7&apos;, or &apos;=&apos;..
        /// </summary>
        internal static string InvalidCredentialSecret {
            get {
                return ResourceManager.GetString("InvalidCredentialSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A credential type cannot be null..
        /// </summary>
        internal static string InvalidCredentialType {
            get {
                return ResourceManager.GetString("InvalidCredentialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A supplied property contained invalid data for CTAP2..
        /// </summary>
        internal static string InvalidCtap2Data {
            get {
                return ResourceManager.GetString("InvalidCtap2Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data provided does not match the expected encoding..
        /// </summary>
        internal static string InvalidDataEncoding {
            get {
                return ResourceManager.GetString("InvalidDataEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not a data tag supported by the YubiKey application..
        /// </summary>
        internal static string InvalidDataTag {
            get {
                return ResourceManager.GetString("InvalidDataTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device must be a FIDO device..
        /// </summary>
        internal static string InvalidDeviceNotFido {
            get {
                return ResourceManager.GetString("InvalidDeviceNotFido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device must be a Keyboard device..
        /// </summary>
        internal static string InvalidDeviceNotKeyboard {
            get {
                return ResourceManager.GetString("InvalidDeviceNotKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device must be a Yubico device..
        /// </summary>
        internal static string InvalidDeviceNotYubico {
            get {
                return ResourceManager.GetString("InvalidDeviceNotYubico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect host challenge length..
        /// </summary>
        internal static string InvalidHostChallengeLength {
            get {
                return ResourceManager.GetString("InvalidHostChallengeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial moving factor must be between 0 and 0xffff0 (1,048,560) and be divisable by 0x10 (16)..
        /// </summary>
        internal static string InvalidImfValue {
            get {
                return ResourceManager.GetString("InvalidImfValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad response to InitializeUpdate..
        /// </summary>
        internal static string InvalidInitializeUpdateResponse {
            get {
                return ResourceManager.GetString("InvalidInitializeUpdateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A YubiOTP APDU was received with instruction number {0}. This instruction is not supported..
        /// </summary>
        internal static string InvalidKeyboardInstruction {
            get {
                return ResourceManager.GetString("InvalidKeyboardInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NDEF configuration data is not formed correctly..
        /// </summary>
        internal static string InvalidNdefConfig {
            get {
                return ResourceManager.GetString("InvalidNdefConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password cannot be null or empty..
        /// </summary>
        internal static string InvalidOathPassword {
            get {
                return ResourceManager.GetString("InvalidOathPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The challenge / response algorithm specified is invalid..
        /// </summary>
        internal static string InvalidOtpChallengeResponseAlgorithm {
            get {
                return ResourceManager.GetString("InvalidOtpChallengeResponseAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP slot..
        /// </summary>
        internal static string InvalidOtpSlot {
            get {
                return ResourceManager.GetString("InvalidOtpSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given the offset, the length of the output buffer was not valid..
        /// </summary>
        internal static string InvalidOutputBuffer {
            get {
                return ResourceManager.GetString("InvalidOutputBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid padding..
        /// </summary>
        internal static string InvalidPadding {
            get {
                return ResourceManager.GetString("InvalidPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN cannot be null or empty..
        /// </summary>
        internal static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN must be 6 to 32 bytes long..
        /// </summary>
        internal static string InvalidPinLength {
            get {
                return ResourceManager.GetString("InvalidPinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN or PUK must be 6, 7, or 8 characters long..
        /// </summary>
        internal static string InvalidPinPukLength {
            get {
                return ResourceManager.GetString("InvalidPinPukLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A PIN or PUK retry count must be greater than 0 and less than 256..
        /// </summary>
        internal static string InvalidPinPukRetryCount {
            get {
                return ResourceManager.GetString("InvalidPinPukRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied data for a PIV Data Object was an invalid length..
        /// </summary>
        internal static string InvalidPivDataObjectLength {
            get {
                return ResourceManager.GetString("InvalidPivDataObjectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied data for a PIV Data Object was invalid..
        /// </summary>
        internal static string InvalidPivDataObjectValue {
            get {
                return ResourceManager.GetString("InvalidPivDataObjectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN-only mode to set a YubiKey. Only None, PinProtected, or PinDerived are allowed..
        /// </summary>
        internal static string InvalidPivPinOnlyMode {
            get {
                return ResourceManager.GetString("InvalidPivPinOnlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of input to a Put Data operation, {0}, was invalid, the maximum is {1}..
        /// </summary>
        internal static string InvalidPivPutDataLength {
            get {
                return ResourceManager.GetString("InvalidPivPutDataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data does not match a supported private key format..
        /// </summary>
        internal static string InvalidPrivateKeyData {
            get {
                return ResourceManager.GetString("InvalidPrivateKeyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property must be exactly {1} bytes long. Only {2} bytes were given..
        /// </summary>
        internal static string InvalidPropertyLength {
            get {
                return ResourceManager.GetString("InvalidPropertyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data does not match a supported public key format..
        /// </summary>
        internal static string InvalidPublicKeyData {
            get {
                return ResourceManager.GetString("InvalidPublicKeyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard layout [{0}] doesn&apos;t have a scancode for [{1}]..
        /// </summary>
        internal static string InvalidScancode {
            get {
                return ResourceManager.GetString("InvalidScancode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot number {0:X2} is not valid for the given operation on the given YubiKey..
        /// </summary>
        internal static string InvalidSlot {
            get {
                return ResourceManager.GetString("InvalidSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status report must be the first and only report returned by the YubiKey..
        /// </summary>
        internal static string InvalidStatusReport {
            get {
                return ResourceManager.GetString("InvalidStatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid status word &quot;{0}&quot;. For this method, the status word must be NoPreciseDiagnosis (0x6F 00)..
        /// </summary>
        internal static string InvalidStatusWordMustBeNoPreciseDiagnosis {
            get {
                return ResourceManager.GetString("InvalidStatusWordMustBeNoPreciseDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The U2F HID error code should be 1 byte long. The supplied error code contains {0} bytes..
        /// </summary>
        internal static string InvalidU2fHidErrorCodeLength {
            get {
                return ResourceManager.GetString("InvalidU2fHidErrorCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A URI path cannot be null or empty..
        /// </summary>
        internal static string InvalidUriPath {
            get {
                return ResourceManager.GetString("InvalidUriPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI scheme must be &apos;otpauth://&apos;..
        /// </summary>
        internal static string InvalidUriScheme {
            get {
                return ResourceManager.GetString("InvalidUriScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyboard connection does not support writing more than 64 bytes to the device..
        /// </summary>
        internal static string KeyboardDataTooBig {
            get {
                return ResourceManager.GetString("KeyboardDataTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flag {0} is not a valid keyboard report flag..
        /// </summary>
        internal static string KeyboardInvalidFlag {
            get {
                return ResourceManager.GetString("KeyboardInvalidFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried writing a keyboard report and unexpectedly recieved no reply..
        /// </summary>
        internal static string KeyboardNoReply {
            get {
                return ResourceManager.GetString("KeyboardNoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to read a status keyboard report and failed..
        /// </summary>
        internal static string KeyboardReadReportFailed {
            get {
                return ResourceManager.GetString("KeyboardReadReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sequence number {0} is outside the range of allowed values..
        /// </summary>
        internal static string KeyboardSequenceOutOfRange {
            get {
                return ResourceManager.GetString("KeyboardSequenceOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YubiKey did not acknowledge a write to the keyboard interface within the alloted time..
        /// </summary>
        internal static string KeyboardTimeout {
            get {
                return ResourceManager.GetString("KeyboardTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to read another keyboard report, but that failed. UnexpectedEOR = {0}, WaitingForTouch = {1}.
        /// </summary>
        internal static string KeyboardUnexpectedEndOfBuffer {
            get {
                return ResourceManager.GetString("KeyboardUnexpectedEndOfBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YubiKey has no visible serial number. Either API visibility is disabled or the YubiKey does not have a serial number..
        /// </summary>
        internal static string KeyHasNoVisibleSerial {
            get {
                return ResourceManager.GetString("KeyHasNoVisibleSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key must be set either explicitly or by specifying that it should be generated before it can be read..
        /// </summary>
        internal static string KeyNotSet {
            get {
                return ResourceManager.GetString("KeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCP03 handshake called out-of-order: loading an external authenticate response before processing the preceding initialize update response is not possible..
        /// </summary>
        internal static string LoadExternalAuthenticateResponsePriorToLoadInitializUpdateResponse {
            get {
                return ResourceManager.GetString("LoadExternalAuthenticateResponsePriorToLoadInitializUpdateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCP03 handshake called out-of-order: loading the response to an initialize update command before building it is not possible..
        /// </summary>
        internal static string LoadInitializeUpdatePriorToBuild {
            get {
                return ResourceManager.GetString("LoadInitializeUpdatePriorToBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration lock code cannot be set to all zeros..
        /// </summary>
        internal static string LockCodeAllZeroNotAllowed {
            get {
                return ResourceManager.GetString("LockCodeAllZeroNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lock code must be {0}-bytes. {1} bytes were specified..
        /// </summary>
        internal static string LockCodeWrongLength {
            get {
                return ResourceManager.GetString("LockCodeWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NDEF record is malformed. Contact Yubico Support if this error persists..
        /// </summary>
        internal static string MalformedNdefRecord {
            get {
                return ResourceManager.GetString("MalformedNdefRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open the management application..
        /// </summary>
        internal static string ManagementApplicationUnavailable {
            get {
                return ResourceManager.GetString("ManagementApplicationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YubiKey is configured for PIN-only, so the management key cannot be changed..
        /// </summary>
        internal static string MgmtKeyCannotBeChanged {
            get {
                return ResourceManager.GetString("MgmtKeyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required property was missing for CTAP2..
        /// </summary>
        internal static string MissingCtap2Data {
            get {
                return ResourceManager.GetString("MissingCtap2Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A KeyCollector delegate is needed but not supplied..
        /// </summary>
        internal static string MissingKeyCollector {
            get {
                return ResourceManager.GetString("MissingKeyCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple exceptions encountered. See inner exceptions for details..
        /// </summary>
        internal static string MultipleExceptions {
            get {
                return ResourceManager.GetString("MultipleExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the YubiKey serial number as the public ID, the Memory&lt;byte&gt; collection must be exactly six bytes..
        /// </summary>
        internal static string MustBeSixBytesForSerial {
            get {
                return ResourceManager.GetString("MustBeSixBytesForSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose either the HMAC-SHA1 or Yubico OTP algorithm for the challenge response..
        /// </summary>
        internal static string MustChooseAlgorithm {
            get {
                return ResourceManager.GetString("MustChooseAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either specify or choose to generate a key..
        /// </summary>
        internal static string MustChooseOrGenerateKey {
            get {
                return ResourceManager.GetString("MustChooseOrGenerateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either specify or choose to generate a private ID..
        /// </summary>
        internal static string MustChooseOrGeneratePrivateId {
            get {
                return ResourceManager.GetString("MustChooseOrGeneratePrivateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either specify a value or choose to use the YubiKey serial number as a public ID..
        /// </summary>
        internal static string MustChooseOrUseSerialAsPublicId {
            get {
                return ResourceManager.GetString("MustChooseOrUseSerialAsPublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify either TOTP or a challenge..
        /// </summary>
        internal static string MustChooseTotpOrChallenge {
            get {
                return ResourceManager.GetString("MustChooseTotpOrChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one available USB capability must be enabled..
        /// </summary>
        internal static string MustEnableOneAvailableUsbCapability {
            get {
                return ResourceManager.GetString("MustEnableOneAvailableUsbCapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one USB interface must be enabled..
        /// </summary>
        internal static string MustEnableOneAvailableUsbInterface {
            get {
                return ResourceManager.GetString("MustEnableOneAvailableUsbInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a keyboard layout to configure a static password..
        /// </summary>
        internal static string MustSpecifyKeyboardLayout {
            get {
                return ResourceManager.GetString("MustSpecifyKeyboardLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must either supply a static password or specify that one should be generated..
        /// </summary>
        internal static string MustSpecifyOrGeneratePassword {
            get {
                return ResourceManager.GetString("MustSpecifyOrGeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NDEF language code is too long..
        /// </summary>
        internal static string NdefLanguageCodeTooLong {
            get {
                return ResourceManager.GetString("NdefLanguageCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value and languageCode specified must fit within a buffer of less than {0} bytes. It requires {1} bytes in total, with value requiring {2} bytes, and languageCode requiring {3} bytes..
        /// </summary>
        internal static string NdefTextTooLong {
            get {
                return ResourceManager.GetString("NdefTextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uri specified must fit within a buffer of less than {0} bytes. The length is {1} after matching with a prefix code of {2}..
        /// </summary>
        internal static string NdefUriTooLong {
            get {
                return ResourceManager.GetString("NdefUriTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active connections for that YubiKey were found..
        /// </summary>
        internal static string NoActiveConnections {
            get {
                return ResourceManager.GetString("NoActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to encode..
        /// </summary>
        internal static string NoDataToEncode {
            get {
                return ResourceManager.GetString("NoDataToEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no YubiKey interface available to communicate with the requested application..
        /// </summary>
        internal static string NoInterfaceAvailable {
            get {
                return ResourceManager.GetString("NoInterfaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no retries remaining for a PIN, PUK, or other authentication element..
        /// </summary>
        internal static string NoMoreRetriesRemaining {
            get {
                return ResourceManager.GetString("NoMoreRetriesRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response data is not available as the ResponseApdu has indicated a failure. Check the SW property or call ThrowIfFailed for more information..
        /// </summary>
        internal static string NoResponseDataApduFailed {
            get {
                return ResourceManager.GetString("NoResponseDataApduFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration of ConnectionType.HidFido devices is not implemented..
        /// </summary>
        internal static string NotImplementedHidFidoEnumeration {
            get {
                return ResourceManager.GetString("NotImplementedHidFidoEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not supported by this version of YubiKey..
        /// </summary>
        internal static string NotSupportedByYubiKeyVersion {
            get {
                return ResourceManager.GetString("NotSupportedByYubiKeyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose either Yubico OTP or HMAC-SHA1, but not both..
        /// </summary>
        internal static string OnlyOneAlgorithm {
            get {
                return ResourceManager.GetString("OnlyOneAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to perform command encoding or response decoding prior to loading the response to initialize update..
        /// </summary>
        internal static string OperationPriorToLoadInitializeUpdate {
            get {
                return ResourceManager.GetString("OperationPriorToLoadInitializeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OTP code must be between 6 and 10 digits..
        /// </summary>
        internal static string OtpCodeDigitRange {
            get {
                return ResourceManager.GetString("OtpCodeDigitRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are values set as ConfigurationFlags that are not valid..
        /// </summary>
        internal static string OtpConfigFlagsInvalid {
            get {
                return ResourceManager.GetString("OtpConfigFlagsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more flags specified are not allowed to be updated..
        /// </summary>
        internal static string OtpConfigFlagsNotUpdatable {
            get {
                return ResourceManager.GetString("OtpConfigFlagsNotUpdatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are values set as ExtendedFlags that are not valid..
        /// </summary>
        internal static string OtpExtendedFlagsInvalid {
            get {
                return ResourceManager.GetString("OtpExtendedFlagsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicting OTP configuration flags: {0} cannot be set with {1}..
        /// </summary>
        internal static string OtpFlagConflict {
            get {
                return ResourceManager.GetString("OtpFlagConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} flag requires the {1} flag to also be set..
        /// </summary>
        internal static string OtpFlagRequired {
            get {
                return ResourceManager.GetString("OtpFlagRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} flag requires all of the {1} flag to also be set..
        /// </summary>
        internal static string OtpFlagRequiredAnd {
            get {
                return ResourceManager.GetString("OtpFlagRequiredAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} flag requires at least one of the flags {1} to also be set..
        /// </summary>
        internal static string OtpFlagRequiredOr {
            get {
                return ResourceManager.GetString("OtpFlagRequiredOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value given to GetYubiKeyFlags is not a valid OtpFlags value..
        /// </summary>
        internal static string OtpFlagsNotValid {
            get {
                return ResourceManager.GetString("OtpFlagsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language code is invalid..
        /// </summary>
        internal static string OtpNdefInvalidLanguageCode {
            get {
                return ResourceManager.GetString("OtpNdefInvalidLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An NDEF slot must be programmed as text or as a URI. Neither of these were specified..
        /// </summary>
        internal static string OtpNdefNoTypeChosen {
            get {
                return ResourceManager.GetString("OtpNdefNoTypeChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifying UTF-16 encoding or a language code does not have any effect when programming a URI into the NDEF slot..
        /// </summary>
        internal static string OtpNdefPropertiesHaveNoEffect {
            get {
                return ResourceManager.GetString("OtpNdefPropertiesHaveNoEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select the NDEF file record. {0}.
        /// </summary>
        internal static string OtpNdefSelectFileFailed {
            get {
                return ResourceManager.GetString("OtpNdefSelectFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An NDEF configuration cannot contain both both text and a URI..
        /// </summary>
        internal static string OtpNdefTypeConflict {
            get {
                return ResourceManager.GetString("OtpNdefTypeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command cannot be performed because none of the slots are configured..
        /// </summary>
        internal static string OtpSlotsNotConfigured {
            get {
                return ResourceManager.GetString("OtpSlotsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping OTP slot configurations is not supported on YubiKeys with firmware version less than 2.3.2..
        /// </summary>
        internal static string OtpSwapCommandNotSupported {
            get {
                return ResourceManager.GetString("OtpSwapCommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are values set as TicketFlags that are not valid..
        /// </summary>
        internal static string OtpTicketFlagsInvalid {
            get {
                return ResourceManager.GetString("OtpTicketFlagsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prefix code specified in the NDEF record is not valid. Prefix codes are between 0 and 35..
        /// </summary>
        internal static string OutOfRangeUriPrefixCode {
            get {
                return ResourceManager.GetString("OutOfRangeUriPrefixCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is not set yet. You should execute the operation before attempting to retrieve the password..
        /// </summary>
        internal static string PasswordNotSetYet {
            get {
                return ResourceManager.GetString("PasswordNotSetYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YubiKey is configured for something incompatible with PIN-only..
        /// </summary>
        internal static string PinOnlyNotPossible {
            get {
                return ResourceManager.GetString("PinOnlyNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private ID must be set either explicitly or by specifying that it should be generated before it can be read..
        /// </summary>
        internal static string PrivateIdNotSet {
            get {
                return ResourceManager.GetString("PrivateIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private identifier must be exactly 6 bytes..
        /// </summary>
        internal static string PrivateIdWrongSize {
            get {
                return ResourceManager.GetString("PrivateIdWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property can only be set to a maximum value of {1}. The value is {2}..
        /// </summary>
        internal static string PropertyValueTooLarge {
            get {
                return ResourceManager.GetString("PropertyValueTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public ID must be set either explicitly or by specifying to use serial number before it can be read..
        /// </summary>
        internal static string PublicIdNotSet {
            get {
                return ResourceManager.GetString("PublicIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public identifier must be between 1 and 16 bytes..
        /// </summary>
        internal static string PublicIdWrongSize {
            get {
                return ResourceManager.GetString("PublicIdWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming a credential is not supported on YubiKeys with firmware version less than 5.3.0..
        /// </summary>
        internal static string RenameCommandNotSupported {
            get {
                return ResourceManager.GetString("RenameCommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method can only be called on a YubiKey that is connected via NFC..
        /// </summary>
        internal static string RequiresNfc {
            get {
                return ResourceManager.GetString("RequiresNfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HMAC-SHA512 algorithm is not supported on YubiKeys with firmware version less than 4.3.1..
        /// </summary>
        internal static string SHA512NotSupported {
            get {
                return ResourceManager.GetString("SHA512NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No YubiKey slot was set. You must select a slot to configure..
        /// </summary>
        internal static string SlotNotSet {
            get {
                return ResourceManager.GetString("SlotNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to select the smart card application. 0x{0:X4}.
        /// </summary>
        internal static string SmartCardPipelineSetupFailed {
            get {
                return ResourceManager.GetString("SmartCardPipelineSetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The static password length must be between 1 and {0} characters..
        /// </summary>
        internal static string StaticPasswordInvalidLength {
            get {
                return ResourceManager.GetString("StaticPasswordInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The StaticTicket flag cannot be changed in a StaticTicketFlags object..
        /// </summary>
        internal static string StaticTicketNotSettable {
            get {
                return ResourceManager.GetString("StaticTicketNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status report must be the first report read by the KeyboardFrameReader..
        /// </summary>
        internal static string StatusReportNotFirstReportRead {
            get {
                return ResourceManager.GetString("StatusReportNotFirstReportRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An input Stream was not readable..
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only USB interfaces are supported by this operation..
        /// </summary>
        internal static string SupportsOnlyUsbInterfaces {
            get {
                return ResourceManager.GetString("SupportsOnlyUsbInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch eject timeout requires the YubiKey to only have the CCID interface enabled..
        /// </summary>
        internal static string TouchEjectTimeoutRequiresCcidOnly {
            get {
                return ResourceManager.GetString("TouchEjectTimeoutRequiresCcidOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The require touch property is not supported on YubiKeys with firmware version less than 4.2.4..
        /// </summary>
        internal static string TouchNotSupported {
            get {
                return ResourceManager.GetString("TouchNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command will block as it is requesting user presence (touch)..
        /// </summary>
        internal static string TouchRequired {
            get {
                return ResourceManager.GetString("TouchRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Triple-DES operation failed..
        /// </summary>
        internal static string TripleDesFailed {
            get {
                return ResourceManager.GetString("TripleDesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification of the current password failed..
        /// </summary>
        internal static string UnableToVerifyOathPassword {
            get {
                return ResourceManager.GetString("UnableToVerifyOathPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected state encountered. This most likely indicates a bug in the SDK. Please report this exception to Yubico Support..
        /// </summary>
        internal static string UnexpectedState {
            get {
                return ResourceManager.GetString("UnexpectedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authenticator returned an unknown FIDO2 status indicating an error..
        /// </summary>
        internal static string UnknownFido2Status {
            get {
                return ResourceManager.GetString("UnknownFido2Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown FIDO error has occurred..
        /// </summary>
        internal static string UnknownFidoError {
            get {
                return ResourceManager.GetString("UnknownFidoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown SCP03 error has occurred..
        /// </summary>
        internal static string UnknownScp03Error {
            get {
                return ResourceManager.GetString("UnknownScp03Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown YubiKey feature..
        /// </summary>
        internal static string UnknownYubiKeyFeature {
            get {
                return ResourceManager.GetString("UnknownYubiKeyFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested algorithm is not supported..
        /// </summary>
        internal static string UnsupportedAlgorithm {
            get {
                return ResourceManager.GetString("UnsupportedAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate provided is not supported as an Attestation Certificate..
        /// </summary>
        internal static string UnsupportedAttestationCert {
            get {
                return ResourceManager.GetString("UnsupportedAttestationCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for user interaction..
        /// </summary>
        internal static string UserInteractionTimeout {
            get {
                return ResourceManager.GetString("UserInteractionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the data to the requested type. Expected only {0} byte(s) of data, but {1} byte(s) were present..
        /// </summary>
        internal static string ValueConversionFailed {
            get {
                return ResourceManager.GetString("ValueConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not valid for the enum type {1}..
        /// </summary>
        internal static string ValueIsNotEnum {
            get {
                return ResourceManager.GetString("ValueIsNotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}, and the first value must be less than the second..
        /// </summary>
        internal static string ValueMustBeBetweenXandY {
            get {
                return ResourceManager.GetString("ValueMustBeBetweenXandY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The HID code map must contain {0} HID codes. The supplied map contains {1}..
        /// </summary>
        internal static string WrongHidCodeMapLength {
            get {
                return ResourceManager.GetString("WrongHidCodeMapLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NDEF record has a type of {0}. Unable to translate it to {1} as requested..
        /// </summary>
        internal static string WrongNdefType {
            get {
                return ResourceManager.GetString("WrongNdefType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AES key must be exactly 16 bytes..
        /// </summary>
        internal static string YubicoKeyWrongSize {
            get {
                return ResourceManager.GetString("YubicoKeyWrongSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Yubico OTP algorithm requires a 6-byte challenge..
        /// </summary>
        internal static string YubicoOtpChallengeLengthInvalid {
            get {
                return ResourceManager.GetString("YubicoOtpChallengeLengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yubico OTP is not compatible with TOTP..
        /// </summary>
        internal static string YubicoOtpNotCompatible {
            get {
                return ResourceManager.GetString("YubicoOtpNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIV management key mutual authentication failed because the YubiKey did not authenticate..
        /// </summary>
        internal static string YubiKeyNotAuthenticatedInPiv {
            get {
                return ResourceManager.GetString("YubiKeyNotAuthenticatedInPiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested operation is not available on non-FIPS YubiKeys..
        /// </summary>
        internal static string YubiKeyNotFips {
            get {
                return ResourceManager.GetString("YubiKeyNotFips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YubiKey Operation Failed [{0}].
        /// </summary>
        internal static string YubiKeyOperationFailed {
            get {
                return ResourceManager.GetString("YubiKeyOperationFailed", resourceCulture);
            }
        }
    }
}
